### ISSUE TITLE
When will this code be released?

### ISSUE THREAD

**Issue by dl-m9** [PJLab-ADG/DiLu#1]
Thanks for your awesome work! I just want to know when will this code be released?  I am looking forward to playing with this project!

**Comment by zijinoier** [comment]
Thanks for the interested in our work!

We do have plans to release the source code, and our goal is to make it publicly available no later than the end of Jan. 2024.

**Comment by zijinoier** [comment]
@Bmithbs  The codes are now release! Thanls again for your interest in our project:)
