### ISSUE TITLE
其他密度的实验

### ISSUE THREAD

**Issue by AHPUymhd** [PJLab-ADG/DiLu#10]
我看论文里面的实验是从道路4密度2开始的，请问你们做了道路4密度1的实验吗，大概有多少的成功率呢，可以达到百分之九十吗，谢谢。

**Comment by AHPUymhd** [comment]
@zijinoier

**Comment by zijinoier** [comment]
We did not perform experiments with lane-4 density-1. However, it is expected to have better performance than lane-4 density-2 since the lower car density simplifies the environment.
