### ISSUE TITLE
Env setting not match 

### ISSUE THREAD

**Issue by Fengtao22** [PJLab-ADG/DiLu#2]
Hi, thanks for sharing your code! I have two questions with respect to your repo: (1) in your yaml file, the target speed level is different from what mentioned in the paper (available speed levels are 10, 15, 20, 25, and 32 units), and (2) how many random seeds do you use to collect the success rate for the paper? From your config.yaml file, it seems only 3 random seeds are used.

**Comment by zijinoier** [comment]
Thank you for your interest in our work! I'd like to clarify your queries:

1. In the yaml file, there is no parameter to configure the target speed level. The values mentioned in the paper are the ones we used in our experiments.

2. As for the random seeds used in our experiments, we state in the paper that "Each setting is repeated 10 times with different seeds".

I hope this clarifies your concerns.

**Comment by Fengtao22** [comment]
Thanks for your quick response and clarification! Yes, my bad. The parameters are defined in the run_dilu.py. So, is the run_dilu.py the script DILU uses in the experiments? For your second comment, my understanding is 10 experiments with different seeds, i.e., total 10 random seeds ? Thanks!

**Comment by zijinoier** [comment]
Yes, you are correct on both counts. 
The run_dilu.py script is indeed the one used in our experiments for DILU. And regarding your second query, you understood correctly – we conducted 10 experiments using 10 different seeds.
