### ISSUE TITLE
hardware conditions

### ISSUE THREAD

**Issue by caichuang0415** [PJLab-ADG/DiLu#3]
Thanks for sharing your codes!
But I want to know what gpu and how many do I need to do the inference and trainning? And how much time?

**Comment by zijinoier** [comment]
For DiLu, all inference and training are conducted through the OpenAI API, so there's no need for local GPU resources for inference or training. Please follow the instructions in the README for guidance on how to use the API effectively.

**Comment by caichuang0415** [comment]
> For DiLu, all inference and training are conducted through the OpenAI API, so there's no need for local GPU resources for inference or training. Please follow the instructions in the README for guidance on how to use the API effectively.

OK Thanks for your reply, I will read them in detail
