### ISSUE TITLE
Quick question realted to the experiment environment

### ISSUE THREAD

**Issue by Daniel-xsy** [PJLab-ADG/DiLu#5]
Thanks for your interesting work. 

I have a quick question related to the environment you use (i.e., highway-env). Is it possible to customize the environment? For example, can I control the trajectory and status (e.g., speed, acceleration) of other vehicles to customize the environment I want for evaluation?

**Comment by zijinoier** [comment]
Thank you for your interest in our work!

Regarding your question about customizing the highway-env, **direct control over the trajectory of vehicles is not supported.** However, you can indeed control vehicle using the speed and steering angle. 
For more details on the control inputs available and how to use them, please refer to the official highway-env documentation: [Highway-env Actions Documentation](https://highway-env.farama.org/actions/).

**Comment by Daniel-xsy** [comment]
Thanks!
