### ISSUE TITLE
The Scenario Descriptor

### ISSUE THREAD

**Issue by jis3613** [PJLab-ADG/DiLu#7]
Hi, first of all, congratulations on your great work!
I think you work has a lot of contributions to autonomous driving community.

Due to my mediocre understanding, I did not fully understand how the Scenario Descriptor transcribes the observed environment into scenario in a natural language.
Could you explain in more details about how the descriptor works (how it changes observed env into natural language form).
And could you specify the code that implements the descriptor part.

I really appreciate your hard work and effort.
Thank you!

**Comment by zijinoier** [comment]
Thanks for your interest in our work!

You can refer to the following code to see how the descriptor works:
https://github.com/PJLab-ADG/DiLu/blob/74c4aa96a8f5816731d5eb5cc1d93add30674287/dilu/scenario/envScenario.py#L372-L384
