### ISSUE TITLE
Some small problem

### ISSUE THREAD

**Issue by yabuke** [PJLab-ADG/DiLu#9]
Hello, first of all, congratulations on having your work accepted by ICLR.

I'm also very interested in your work, but I have a few questions I hope the authors can address:

1. Where does the experience used in the simulation come from? In Figure 6 of the paper, a comparison is made with Memory libraries containing 5, 20, and 40 experiences, but in the project's Memory library, there are only 21 experiences. Why 21? Were 5 and 20 randomly selected from it during simulation? How was the scenario with 40 experiences completed? Do readers need to simulate it themselves and then use the reflection module to generate it?

2. Does the Memory library need to be updated in real time? From the project source code, it seems like you don't update the Memory library used in the simulation in real time, but instead write the experiences generated by the reflection module to another Memory library. In theory, doesn't this need real-time updating?

3. Diversity of experiences in the Memory library: If the Memory module doesn't need to be updated in real time, and a fixed-size Memory library is selected for simulation use, how do you ensure the diversity of experiences in the Memory library?

**Comment by zijinoier** [comment]
Thank you for your kind words and interest in our work. I'd be happy to address your questions:

1. The 21 experiences in the repository closely resemble the 20 experiences reported in the paper. For the scenario with 40 experiences, users need to accumulate additional experiences themselves. As for the 5 experiences, you can sample 5 out of the provided 21 experiences.

2. No, the Memory module does not need to be updated in real-time. It is updated offline. The experiences generated by the reflection module are written to a separate Memory library.

3. To ensure the diversity of experiences in the Memory library, we sample the experiences before adding them, as illustrated in Figure 5: Reflection module in our paper. This sampling process helps maintain a variety of experiences.

Please feel free to reach out if you have any further queries.
